# Generated by Django 3.0.1 on 2019-12-26 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sertifika İsmi')),
                ('date', models.DateField(verbose_name='Alınan Tarih')),
                ('getWhere', models.CharField(max_length=50, verbose_name='Alınan Yer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_number', models.CharField(max_length=11, verbose_name='Telefon numarası')),
                ('adresses', models.CharField(max_length=50, verbose_name='Adres')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobNewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTag', models.CharField(max_length=50, verbose_name='İş Başlığı')),
                ('employerCompany', models.CharField(max_length=50, verbose_name='İşveren Firma')),
                ('jobDescription', models.TextField(verbose_name='İş Tanımı ve Aranan özellikler')),
                ('pozitionInformation', models.TextField(verbose_name='Pozisyon Bilgileri')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdInformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_no', models.CharField(max_length=11, verbose_name='Tc Kimlik Numarası')),
                ('birth_place', models.CharField(max_length=20, verbose_name='Doğum Yeri')),
                ('birth_day', models.DateTimeField(verbose_name='Doğum Tarihi')),
                ('city_of_live', models.CharField(max_length=20, verbose_name='Yaşanılan yer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignLanguageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, verbose_name='Yabancı Dil')),
                ('language_level', models.CharField(max_length=100, verbose_name='Yabancı Dil Seviyesi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationInformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduated_from_highscool', models.CharField(max_length=100, verbose_name='Mezun Olunan lise')),
                ('graduated_from_univesity', models.CharField(max_length=100, verbose_name='Mezun Olunan Üniversite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='CvModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceftificatedinf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.CertificatedModel')),
                ('continf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.ContactInformationModel')),
                ('einformation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.EducationInformationModel')),
                ('flanguage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.ForeignLanguageModel')),
                ('idinf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.IdInformationModel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeCompany', models.CharField(max_length=50, verbose_name='Çalıştığı firma')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
